---

name: Deploy

on:
  push:
    branches: [master]

env:
  AWS_DEFAULT_REGION: us-west-2

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Run build
        run: |
          npm ci
          npm run build

      - name: Upload Frontend to S3
        working-directory: ${{ env.FRONTEND_DIRECTORY }}
        run: |
          aws s3 cp dist/ s3://miboda.party/ --recursive

      - name: Outputs
        run: |
          echo "Frontend URL: http://miboda.party.s3-website-us-west-2.amazonaws.com/"
